import { Resend } from "resend";

if (!process.env.RESEND_API_KEY) {
  throw new Error("RESEND_API_KEY environment variable is required");
}

const resend = new Resend(process.env.RESEND_API_KEY);

export interface PackagingReminderData {
  orderNumber: string;
  orderId: string;
  requiredPackagingMaterials: string[];
  triggerStageName: string;
  percentageReached: number;
  organizationName: string;
}

export interface EmailRecipient {
  email: string;
  name?: string;
}

export async function sendPackagingReminder(
  recipients: EmailRecipient[],
  reminderData: PackagingReminderData
) {
  const {
    orderNumber,
    orderId,
    requiredPackagingMaterials,
    triggerStageName,
    percentageReached,
    organizationName,
  } = reminderData;

  const materialsListHtml = requiredPackagingMaterials
    .map((material) => `<li style="margin-bottom: 8px;">${material}</li>`)
    .join("");

  const html = `
    <div style="font-family: system-ui, -apple-system, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px;">
      <div style="background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; padding: 30px; border-radius: 12px 12px 0 0; text-align: center;">
        <h1 style="margin: 0; font-size: 28px; font-weight: 600;">📦 Packaging Reminder</h1>
        <p style="margin: 10px 0 0 0; font-size: 16px; opacity: 0.9;">Order #${orderNumber}</p>
      </div>
      
      <div style="background: #f8fafc; padding: 30px; border-radius: 0 0 12px 12px; border: 1px solid #e2e8f0;">
        <div style="background: #ffffff; padding: 25px; border-radius: 8px; margin-bottom: 20px; border: 1px solid #e2e8f0;">
          <h2 style="color: #1e293b; margin: 0 0 15px 0; font-size: 20px;">Time to Order Packaging Materials!</h2>
          <p style="color: #475569; line-height: 1.6; margin: 0 0 20px 0;">
            <strong>${percentageReached}%</strong> of items for Order #<strong>${orderNumber}</strong> have reached the 
            <strong>"${triggerStageName}"</strong> stage. Please consider ordering the following packaging materials 
            if you haven't already, keeping their respective lead times in mind:
          </p>
          
          <div style="background: #f1f5f9; padding: 20px; border-radius: 6px; border-left: 4px solid #3b82f6;">
            <h3 style="color: #1e293b; margin: 0 0 15px 0; font-size: 16px;">Required Packaging Materials:</h3>
            <ul style="color: #475569; margin: 0; padding-left: 20px; line-height: 1.6;">
              ${materialsListHtml}
            </ul>
          </div>
        </div>
        
        <div style="background: #ffffff; padding: 25px; border-radius: 8px; border: 1px solid #e2e8f0;">
          <h3 style="color: #1e293b; margin: 0 0 15px 0; font-size: 18px;">💡 Next Steps</h3>
          <div style="color: #475569; line-height: 1.6;">
            <p style="margin: 0 0 10px 0;">• Review the materials list above</p>
            <p style="margin: 0 0 10px 0;">• Consider each material's lead time when ordering</p>
            <p style="margin: 0 0 10px 0;">• Order the longest lead-time materials first</p>
            <p style="margin: 0;">• Update your inventory once materials arrive</p>
          </div>
        </div>
        
        <div style="text-align: center; margin-top: 25px; padding-top: 20px; border-top: 1px solid #e2e8f0;">
          <p style="color: #64748b; font-size: 14px; margin: 0;">
            This reminder was automatically generated by Trakure for ${organizationName}
          </p>
        </div>
      </div>
    </div>
  `;

  const text = `
Packaging Reminder - Order #${orderNumber}

${percentageReached}% of items for Order #${orderNumber} have reached the "${triggerStageName}" stage.

Required Packaging Materials:
${requiredPackagingMaterials.map((material) => `• ${material}`).join("\n")}

Please consider ordering these materials if you haven't already, keeping their respective lead times in mind.

Next Steps:
• Review the materials list above
• Consider each material's lead time when ordering  
• Order the longest lead-time materials first
• Update your inventory once materials arrive

This reminder was automatically generated by Trakure for ${organizationName}.
  `;

  try {
    const result = await resend.emails.send({
      from: process.env.RESEND_FROM_EMAIL || "Trakure <noreply@trakure.com>",
      to: recipients.map((r) => r.email),
      subject: `📦 Packaging Reminder: Order #${orderNumber} (${percentageReached}% Complete)`,
      html,
      text,
      tags: [
        { name: "type", value: "packaging-reminder" },
        { name: "order_id", value: orderId },
        { name: "organization", value: organizationName },
      ],
    });

    console.log("📧 Packaging reminder email sent successfully:", {
      orderNumber,
      orderId,
      recipients: recipients.map((r) => r.email),
      emailId: result.data?.id,
    });

    return result;
  } catch (error) {
    console.error("❌ Failed to send packaging reminder email:", {
      orderNumber,
      orderId,
      recipients: recipients.map((r) => r.email),
      error: error instanceof Error ? error.message : "Unknown error",
    });
    throw error;
  }
}
